---

# ansible-playbook --ask-vault-pass node.yml -v

- hosts: localhost
  become: yes

  tasks: 
   - name: Install nodejs and npm
     apt:
       pkg: "{{ item }}"
       state: installed
       update_cache: true
     with_items:
       - nodejs
       - npm
   
   - name: Include vars from the vault
     include_vars:
       file: creds.yml
     no_log: true
   
   - name: Install the dependencies for aws.js
     command: npm install
     args:
       chdir: /home/vagrant/Project/Milestone1

   - name: Delete inventory and dns.json file
     file: 
       path: "{{ item }}"
       state: absent
     with_items:
       - inventory
       - dns.json

   -  name: Run aws.js for Jenkins
      command: nodejs aws.js Jenkins
      args:
        chdir:  /home/vagrant/Project/Milestone1
      environment:
        AWSAccessKeyId : "{{ AWSAccessKeyId }}"
        AWSSecretKey : "{{ AWSSecretKey }}"  

...     